export default {
    name: "rdfa_primer",
    prefix: "rdfa_primer",
    dir: "rdfa/examples/rdfa_primer",
    base: "http://test.org",
    tests: [
        ["example02", "2.1.1.1 Hints on Social Networking Sites"],
        ["example04", "2.1.1.2 Links with Flavor"],
        ["example06", "2.1.1.3 Setting a Default Vocabulary"],
        ["example07", "2.1.1.3 Setting a Default Vocabulary"],
        ["example08", "2.1.1.3 Setting a Default Vocabulary"],
        ["example09", "2.1.1.3 Setting a Default Vocabulary"],
        ["example10", "2.1.1.4 Multiple Items per Page"],
        ["example11", "2.1.1.4 Multiple Items per Page"],
        ["example15", "2.1.2.1 Contact Information"],
        ["example17", "2.1.2.2 Describing Social Networks"],
        ["example18", "2.1.2.2 Describing Social Networks"],
        ["example19", "2.1.2.2 Describing Social Networks"],
        ["example20", "2.1.2.2 Describing Social Networks"],
        ["example22", "2.1.3 Repeated Patterns"],
        ["example23", "2.1.4 Internal References"],
        ["example24", "2.1.4 Internal References"],
        ["example25", "2.1.4 Internal References"],
        ["example26", "2.1.4 Internal References"],
        ["example27", "2.1.5 Using Multiple Vocabularies"],
        ["example28", "2.1.5 Using Multiple Vocabularies"],
        ["example29", "2.1.5 Using Multiple Vocabularies"],
        ["example30", "2.1.5.1 Repeating properties"],
        ["example31", "2.1.5.1 Repeating properties"],
        ["example32", "2.1.5.1 Repeating properties"],
        ["example33", "2.1.5.2 Default Prefixes (Initial Context)"],
        ["example35", "2.2.1 Using the content attribute"],
        ["example36", "2.2.1 Using the content attribute"],
        ["example39", "2.2.2 Datatypes"],
        ["example40", "2.2.3 Alternative for setting the context"],
        ["example41", "2.2.3 Alternative for setting the context"],
        ["example42", "2.2.3 Alternative for setting the context"],
        ["example43", "2.2.3 Alternative for setting the context"],
        ["example44", "2.2.3 Alternative for setting the context"],
        ["example45", "2.2.4 Alternative for setting the property"],
        ["example46", "2.2.4 Alternative for setting the property"],
    ],
};
