export default {
  name: "earl_html5",
  prefix: "earl_reports_html5",
  dir: "rdfa/examples/earl_html5",
  base: "http://rdfa.info/test-suite/test-cases/rdfa1.1/html5",
  tests: [
    ["example0001", "Predicate establishment with @property"],
    ["example0006", "@rel and @rev"],
    ["example0007", "@rel, @rev, @property, @content"],
    ["example0008", "empty string @about"],
    ["example0009", "@rev"],
    ["example0010", "@rel, @rev, @href"],
    ["example0014", "@datatype, xsd:integer"],
    ["example0015", "meta and link"],
    ["example0017", "Related blanknodes"],
    ["example0018", "@rel for predicate"],
    ["example0020", "Inheriting @about for subject"],
    ["example0021", "Subject inheritance with no @about"],
    ["example0023", "@id does not generate subjects"],
    ["example0025", "simple chaining test"],
    ["example0026", "@content"],
    ["example0027", "@content, ignore element content"],
    ["example0029", "markup stripping with @datatype"],
    ["example0030", "omitted @about"],
    ["example0031", "simple @resource"],
    ["example0032", "@resource overrides @href"],
    ["example0033", "simple chaining test with bNode"],
    ["example0034", "simple img[@src] test"],
    ["example0035", "@src/@href test"],
    ["example0036", "@src/@resource test"],
    ["example0037", "@src/@resource test"],
    ["example0038", "@rev - img[@src] test"],
    ["example0039", "@rev - img[@src] test"],
    ["example0048", "@typeof with @about and @rel present, no @resource"],
    ["example0049", "@typeof with @about, no @rel or @resource"],
    ["example0050", "@typeof without anything else"],
    ["example0051", "@typeof with a single @property"],
    ["example0052", "@typeof with @resource and nothing else"],
    [
      "example0053",
      "@typeof with @resource and nothing else, with a subelement",
    ],
    ["example0054", "multiple @property"],
    ["example0055", "multiple @rel"],
    [
      "example0056",
      "@typeof applies to @about on same element with hanging rel",
    ],
    ["example0057", "hanging @rel creates multiple triples"],
    ["example0059", "multiple hanging @rels with multiple children"],
    ["example0060", "UTF-8 conformance"],
    [
      "example0063",
      "@rel in head using reserved XHTML value and empty-prefix CURIE syntax",
    ],
    ["example0064", "@about with safe CURIE"],
    ["example0065", "@rel with safe CURIE"],
    ["example0066", "@about with @typeof in the head"],
    ["example0067", "@property in the head"],
    ["example0068", "Relative URI in @about"],
    ["example0069", "Relative URI in @href"],
    ["example0070", "Relative URI in @resource"],
    ["example0071", "No explicit @about"],
    ["example0072", "Relative URI in @about (with XHTML base in head)"],
    ["example0073", "Relative URI in @resource (with XHTML base in head)"],
    ["example0074", "Relative URI in @href (with XHTML base in head)"],
    ["example0075", "Reserved word 'license' in @rel with no explicit @about"],
    ["example0080", "@about overrides @resource in incomplete triples"],
    ["example0083", "multiple ways of handling incomplete triples"],
    [
      "example0084",
      "handling incomplete triples, this time with both @rel and @rev",
    ],
    ["example0088", "Interpretation of the CURIE (_:)"],
    ["example0089", "@src sets a new subject (@typeof)"],
    ["example0091", "Non-reserved, un-prefixed CURIE in @property"],
    [
      "example0093",
      "XMLLiteral content with explicit @datatype (user-data-typed literal)",
    ],
    ["example0099", "Preservation of white space in literals"],
    ["example0104", "rdf:value"],
    ["example0106", "chaining with empty value in inner @rel"],
    ["example0107", "no garbage collecting bnodes"],
    ["example0110", "bNode generated even though no nested @about exists"],
    ["example0111", "two bNodes generated after three levels of nesting"],
    ["example0112", 'plain literal with datatype=""'],
    ["example0115", "XML Entities must be supported by RDFa parser"],
    ["example0117", "Fragment identifiers stripped from BASE"],
    ["example0118", "empty string is not equivalent to NULL - @about"],
    ["example0119", "[prefix:] CURIE format is valid"],
    ["example0120", "[:] CURIE format is valid"],
    ["example0122", "[] does not set the object"],
    ["example0126", "Multiple @typeof values"],
    ["example0134", "Uppercase reserved words"],
    ["example0140", "Blank nodes identifiers are not allowed as predicates"],
    ["example0174", "Support single character prefix in CURIEs"],
    ["example0175", "IRI for @property is allowed"],
    ["example0176", "IRI for @rel and @rev is allowed"],
    ["example0176b", "IRI for @rel and @rev is allowed"],
    ["example0177", "@prefix"],
    ["example0178", "@prefix with multiple mappings"],
    ["example0182", "prefix locality"],
    ["example0186", "@vocab after subject declaration"],
    ["example0187", "@vocab redefinition"],
    ["example0188", "@vocab only affects predicates"],
    ["example0189", "@vocab overrides default term"],
    ["example0190", "term case insensitivity"],
    ["example0196", "process explicit XMLLiteral"],
    ["example0197", "TERMorCURIEorAbsURI requires an absolute URI"],
    ["example0206", "Usage of Initial Context"],
    ["example0207", "Vevent using @typeof"],
    [
      "example0213",
      "Datatype generation for a literal with XML content, version 1.1",
    ],
    ["example0214", 'Root element has implicit @about=""'],
    [
      "example0216",
      "Proper character encoding detection in spite of large headers",
    ],
    ["example0217", "@vocab causes rdfa:usesVocabulary triple to be added"],
    ["example0218", "@inlist to create empty list"],
    ["example0219", "@inlist with literal"],
    ["example0220", "@inlist with IRI"],
    ["example0221", "@inlist with hetrogenious membership"],
    ["example0224", "@inlist hanging @rel"],
    ["example0225", "@inlist on different elements with same subject"],
    ["example0228", "alternate for test 0040: @rev - @src/@resource test"],
    ["example0229", "img[@src] test with omitted @about"],
    ["example0231", "Set image license information"],
    [
      "example0232",
      "@typeof with @rel present, no @href, @resource, or @about",
    ],
    ["example0233", "@typeof with @rel and @resource present, no @about"],
    [
      "example0246",
      "hanging @rel creates multiple triples, @typeof permutation",
    ],
    ["example0247", "Multiple incomplete triples"],
    ["example0248", "multiple ways of handling incomplete triples (with @rev)"],
    [
      "example0249",
      "multiple ways of handling incomplete triples (with @rel and @rev);",
    ],
    [
      "example0250",
      "Checking the right behaviour of @typeof with @about, in presence of @property",
    ],
    ["example0251", "lang"],
    ["example0252", "lang inheritance"],
    ["example0253", 'plain literal with datatype="" and lang preservation'],
    [
      "example0254",
      '@datatype="" generates plain literal in presence of child nodes',
    ],
    ["example0255", 'lang="" clears language setting'],
    [
      "example0257",
      "element with @property and no child nodes generates empty plain literal",
    ],
    ["example0259", "XML+RDFa Initial Context"],
    ["example0261", "White space preservation in XMLLiteral"],
    [
      "example0262",
      "Predicate with @property, with white spaces before and after the attribute value",
    ],
    [
      "example0263",
      "@property appearing on the html element yields the base as the subjects",
    ],
    [
      "example0264",
      "@property appearing on the head element gets the subject from parent",
    ],
    [
      "example0265",
      "@property appearing on the head element gets the subject from parent",
    ],
    [
      "example0266",
      "@property without @content or @datatype, typed object set by @href and @typeof",
    ],
    [
      "example0267",
      "@property without @content or @datatype, typed object set by @resource and @typeof",
    ],
    [
      "example0268",
      "@property without @content or @datatype, typed object set by @src and @typeof",
    ],
    ["example0269", "Use of @property in HEAD without explicit subject"],
    [
      "example0271",
      "Use of @property in HEAD with explicit parent subject via @about",
    ],
    ["example0272", "time element with @datetime an xsd:date"],
    ["example0273", "time element with @datetime an xsd:time"],
    ["example0274", "time element with @datetime an xsd:dateTime"],
    ["example0275", "time element with value an xsd:date"],
    ["example0276", "time element with value an xsd:time"],
    ["example0277", "time element with value an xsd:dateTime"],
    ["example0278", "@content overrides @datetime"],
    ["example0279", "@datatype used with @datetime overrides default datatype"],
    ["example0281", "time element with @datetime an xsd:gYear"],
    ["example0282", "time element with @datetime an xsd:gYearMonth"],
    [
      "example0283",
      "time element with @datetime an invalid datatype generates plain literal",
    ],
    [
      "example0284",
      "time element not matching datatype but with explicit @datatype",
    ],
    [
      "example0287",
      "time element with @datetime an xsd:dateTime with TZ offset",
    ],
    [
      "example0287b",
      "time element with @datetime an xsd:dateTime with TZ offset",
    ],
    [
      "example0289",
      "@href becomes subject when @property and @content are present",
    ],
    [
      "example0290",
      "@href becomes subject when @property and @datatype are present",
    ],
    ["example0291", "@href as subject overridden by @about"],
    [
      "example0292",
      "@about overriding @href as subject is used as parent resource",
    ],
    ["example0293", "Testing the ':' character usage in a CURIE"],
    ["example0296", "@property does set parent object without @typeof"],
    ["example0297", "@about=[] with @typeof does not create a new subject"],
    ["example0298", "@about=[] with @typeof does not create a new object"],
    [
      "example0299",
      "@resource=[] with @href or @src uses @href or @src (@rel)",
    ],
    [
      "example0300",
      "@resource=[] with @href or @src uses @href or @src (@property",
    ],
    [
      "example0301",
      "@property with @typeof creates a typed_resource for chaining",
    ],
    ["example0302", "@typeof with different content types"],
    [
      "example0303",
      "For HTML+RDFa, remove term elements of @rel/@rev when on same element as @property",
    ],
    ["example0311", "Ensure no triples are generated when @property is empty"],
    ["example0312", "Mute plain @rel if @property is present"],
    ["example0315", "@property and @typeof with incomplete triples"],
    [
      "example0316",
      "@property and @typeof with incomplete triples (href variant)",
    ],
    ["example0317", "@datatype inhibits new @property behavior"],
    [
      "example0318",
      "Setting @vocab to empty strings removes default vocabulary",
    ],
    ["example0321", "rdfa:copy to rdfa:Pattern"],
    ["example0322", "rdfa:copy for additional property value"],
    ["example0323", "Multiple references to rdfa:Pattern"],
    ["example0324", "Multiple references to rdfa:Pattern"],
    ["example0325", "Multiple references to rdfa:Pattern creating a resource"],
    ["example0326", "rdfa:Pattern removed only if referenced"],
    ["example0327", "rdfa:Pattern chaining"],
    ["example0328", "@content overrides the content of the time element."],
    ["example0329", "Recursive triple generation"],
    ["example0330", "@datatype overrides inherited @lang"],
    ["example0331", "@datatype overrides inherited @lang, with @content"],
    [
      "example0332",
      "Empty @datatype doesn't override inherited @lang, with @content",
    ],
    ["example0333", "@content overrides @datetime (with @datatype specified)"],
    [
      "example0334",
      "@resource changes the current subject for the nested elements",
    ],
  ],
};
